name: Check URL links

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Source Files
        uses: actions/checkout@v2

        - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
            ruby-version: 2.6.x

        - name: Validate URL links
        run: |
            gem install awesome_bot
            awesome_bot -f README.md --allow-ssl
